export const CURRENT_QUESTION_KEY = "CURRENT_QUESTION_KEY";
export const QUIZ_STATUS_KEY = "QUIZ_STATUS_KEY";
export const CURRENT_SELECTED_OPTIONS_KEY = "CURRENT_SELECTED_OPTIONS_KEY";
export const VIOLATIONS_KEY = "VIOLATIONS_KEY";
export const TOTAL_SCORE_KEY = "TOTAL_SCORE_KEY";
export const IS_FULL_SCREEN_KEY = "IS_FULL_SCREEN_KEY";