
//----------Quiz Action   Types---------
//export const ADD_QUIZ_LIST = 'ADD_QUIZ_LIST'
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
export const SET_CURRENT_SELECTED_OPTION = 'SET_CURRENT_SELECTED_OPTION';
//export const SET_SELECTED_OPTION = 'SET_SELECTED_OPTION';
export const INCREMENT_VIOLATIONS = 'INCREMENT_VIOLATIONS';
export const SET_TOTAL_SCORE = 'SET_TOTAL_SCORE';
export const SET_QUIZ_STATUS = 'SET_QUIZ_STATUS';
export const ENABLE_SUBMIT_BTN = 'ENABLE_SUBMIT_BTN';
export const RESET_QUIZ = 'RESET_QUIZ';
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN';

